# Generated by Django 3.1.3 on 2020-11-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateField(default='2020-11-19'),
        ),
    ]
