# Generated by Django 3.1.3 on 2020-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20201119_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='categoria',
            field=models.CharField(choices=[('geral', 'Geral'), ('tecnologia', 'Tecnologia'), ('saude', 'Saúde'), ('negocios', 'Negócios'), ('entretenimento', 'Entretenimento'), ('esportes', 'Esportes')], default='geral', max_length=50),
        ),
    ]
